server:
  port: 8080

spring:
  application:
    name: shopapp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: true

open:
  api:
    title: Api document
    version: 1.0.0
    description: This is Api
    serverUrl: http://localhost:8080/
    serverName: Server local
    group: shopapp-api
    packagesToScan: com.example.shopapp.controller

api:
  prefix: api/v1

jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: rCuZp2ZZHonSILWR7CPmPPQoFVMxF0XryI3L2v2Ku/0=